import 'package:cloud_firestore/cloud_firestore.dart';

class ChairModel {
  String docId,id, title, picture, description;
  DateTime date;
  bool status;

  ChairModel({
    this.docId, //for firestore document id
    this.id, // for chair code ( they are auto generated by the machine that manufacture the chairs)
    this.title,
    this.picture,
    this.description,
    this.date,
    this.status,
  });

  List<ChairModel> fromQuery(QuerySnapshot snapshot) {
    return snapshot.docs.map((doc) {
      return ChairModel(
          docId: doc.get('docId'),
          id: doc.get('id'),
          title: doc.get('title'),
          picture: doc.get('picture'),
          description: doc.get('description'),
          date: doc.get('date').toDate(),
          status: doc.get('status'));
    }).toList();
  }

  Map<String, dynamic> toMap() {
    return {
      'docId': this.docId,
      'id': this.id,
      'title': this.title,
      'picture': this.picture,
      'description': this.description,
      'date': this.date,
      'status': this.status,
    };
  }

  factory ChairModel.fromMap(Map<String, dynamic> map) {
    return ChairModel(
      docId: map['docId'] as String,
      id: map['id'] as String,
      title: map['title'] as String,
      picture: map['picture'] as String,
      description: map['description'] as String,
      date: map['date'] as DateTime,
      status: map['status'] as bool,
    );
  }

  String getStatus(){
    return this.status ? 'Open':'Closed';
  }

}
